### ISSUE TITLE
No paired reads?

### ISSUE THREAD

**Issue by dpellow** [nshalon/DomCycle#2]
After changing the parse_fastg script to be able to parse metaspades graphs I am still running into problems with the paired end reads. I am getting the following error:

```
Pairing reads...
Traceback (most recent call last):
  File "pair_reads.py", line 58, in <module>
    print("Percent reads with a pair", round(100*(len(id_to_stats.keys()) - len(singletons)) / len(id_to_stats.keys()),2))
ZeroDivisionError: division by zero
```
I believe this means it thinks there are no paired-end reads in the sample I am running on, but that doesn't seem right. Maybe there is some problem in how I created the sam files. Do you have a recommended way to do that?

**Comment by nshalon** [comment]
Hi, thanks for the note.

May I ask what's the difference in format between the metaspades graph you are using and the FASTG graph provided in `ex/`? Internally, I call bwa mem to create the SAM files -- can you check whether the files filter_R1table and and R1table are empty? If the former is empty and the latter is not, then the reads are being filtered out for some reason.

**Comment by dpellow** [comment]
Both R1table and filter_R1table are empty. I guess that the input file is not in the expected format and I'm not sure how to generate a file in the expected format. Here is what I did:
```
bwa mem -t 50 assembly_graph.fastg /path/to/reads1.fastq /path/to/reads2.fastq | samtools view -buS -@ 50 - > mg_reads_v_assembly_fastg.bam
samtools view -h -f 0x40 mg_reads_v_assembly_fastg.bam > mg_reads_v_fastg_1.sam
samtools view -h -f 0x80 mg_reads_v_assembly_fastg.bam > mg_reads_v_fastg_2.sam
```
That's what I understood to do based on the description, but I guess something is wrong. Can you give the full set of commands used to generate the input files?

My version of metaspades breaks the sequences so that all lines are 60 characters. I'm pretty sure that is legal fastg/fasta format according to the spec.
This means that the processing that depends on the line number mod 2/4 doesn't work. I just checked `line[0] == >` for header lines and assume all other lines are sequence. Here is how I modified parse_fastg.py:
```
with open(args.ifn_fastg) as fastg:
    for line in fastg:
        if line[0] == '>':
            line = line.replace('>','')
            line = line.replace(';',':')
            line = line.split(':')
            contig = line[0]
            contig = contig.replace("'","")
            contig = contig.replace(" ","")
            length_contig = int(contig.split("_")[3])
            contig_to_length[contig] = length_contig
            contig_to_sequence[contig] = ""
        else:
            sequence = line.rstrip()
            contig_to_sequence[contig] += sequence
        
...

with open(args.ifn_fastg) as fastg:
    for line in fastg:
        if line[0] != ">":
            continue

...
```

**Comment by nshalon** [comment]
Got it -- thanks for pointing out that difference in the FASTG format. I'll adapt the script accordingly.

Generally, I'm mapping reads to the FASTA, not the FASTG, so I imagine that is one of the problems. Can you send me an email at nitanshalon at gmail dot com with a link to the reads, assembly (fasta), and SAM you're using so I can take a closer look? Much appreciated.

E: For reference, these are the only calls I'm making to create the input mapping file:
bwa mem $(assembly) $(R1.fastq) > R1_map.sam
bwa mem $(assembly) $(R2.fastq) > R2_map.sam

**Comment by nshalon** [comment]
Hi,

Closing this issue -  assuming it is resolved. The issue seemed to have stemmed from mismatched sequence headers in the input FASTG vs the mapping (pipeline is indiscriminate for spades vs megahit assemblies). We have implemented a workaround that should take care and address this issue. Please let me know if not.
