### ISSUE TITLE
Same contigs name in FASTA and FASTG

### ISSUE THREAD

**Issue by palomo11** [nshalon/DomCycle#3]
Hi, in the README it says:

"It is important that the contig names in the supplied FASTG match the contig names in the FASTA files that were used to create the .sam files."

However, when I do:
megahit_core contig2fastg 127 k127.contigs.fa > k127.contigs.fastg

the contigs names change. E.g.:

fasta file:
>k127_2649552 flag=0 multi=1.0000 len=147
>k127_4769184 flag=0 multi=1.0000 len=143
>k127_2914506 flag=0 multi=1.0000 len=159
>k127_0 flag=0 multi=1.0000 len=152

fastg file:
>NODE_1_length_147_cov_1.0000_ID_1:NODE_3038909_length_132_cov_1.0000_ID_6077817';
>NODE_1_length_147_cov_1.0000_ID_1':NODE_713450_length_144_cov_1.0000_ID_1426899';
>NODE_2_length_143_cov_1.0000_ID_3:NODE_1649577_length_402_cov_1.0000_ID_3299153;
>NODE_2_length_143_cov_1.0000_ID_3':NODE_741621_length_160_cov_1.0000_ID_1483241;
>NODE_3_length_159_cov_1.0000_ID_5:NODE_352489_length_177_cov_1.0000_ID_704977';

Is there any easy way to keep the names in both files?

Thanks in advance.

**Comment by eitanyaffe** [comment]
We added a helper script (pl/rename_fastg.pl) that reverts contig names in the FASTG file, which can be used prior to running DomCycle. See details in updated README.

**Comment by palomo11** [comment]
Thanks for sharing the scripts. I have tried it but I'm getting an error:

```
$ megahit_toolkit contig2fastg 127 k127.contigs.fa > k127.contigs.fastg
$ perl rename_fastg.pl k127.contigs.fa k127.contigs.fastg k127.contigs_rename.fastg
reading fasta file: k127.contigs.fastg
number of contigs: 10598184
traversing fastg file to build map: k127.contigs.fa
sequence mismatch, make sure fasta and fastg are compatible at /work/ese-alexp/scripts/rename_fastg.pl line 74, <IN> line 5.
```

the fast and fastg files:

```
$ head k127.contigs.fa
>k127_2649552 flag=0 multi=1.0000 len=147
AGCCAGAGAGGACAATCATCGACCAGGTTGAAGTCAAGTACCATACCAATGACATACTTCATGGCCTCCCTTGCTTTGGTTGATGGAAGACATGACGCTGTAGGCGCAGACATGATGTCAGTTACCCGTAATCATCAAGGAGGCTTC
>k127_4769184 flag=0 multi=1.0000 len=143
TCTGTGTTTAATCGCATCGGCATGACCGACGTTGGATGCATTGCAACAAAGCGACGGCGATGACATCCATAGAGATGGCTTTTAGTCTAGATGACTATTTTTCCTTTTGGTCGGCATTCAGATAGCATGATTTGCCACTATTA
>k127_2914506 flag=0 multi=1.0000 len=159
AAGATGGTGAAACAAACTTGGCGGATCTATTGACAAAGGTGGTTACGGGTCAGAAGAGATGGGATTTTTGCTATTGTTTATTTTGTTGAGTTGGTCTAACCCATGCCAGTCGAAAGAGATCGGAGGCTTTATAATATGGGTTGATGTATGGTAGAGTGT
>k127_0 flag=0 multi=1.0000 len=152
TAACAGTTCGGCTGAGAACTCTAAGGAGACTGCCTACGCAAGTAGGAGGAAGGTGAGGACGACGTCAAGTCATCATGGCCCTTACGTCCAGGGCTACACACGTGCTACAATGGGATATACAAAGAGCGGCAATACGGTGACGTGGAGCAAAT
>k127_1324780 flag=0 multi=4.2381 len=232
GTGCTGTCATATATCAAGGGCGGCAGCACCGCAGAGGAGCCCAGCACCTACAACCACAAACTTGTGGTAAAAGTCAACAACTGTAAAATGACAAACGCACACACGCACACACACACACACACACACAGTGTCACACGAGAAAATCGAACGTGCTCTTGTGTTGTGTGTGCCTGTACGTGTTGTGTGAGCAGTTCTGCTGTACTTCATCGGTGCGATGCGCAGGACGGCGATG
```

```
$ head k127.contigs.fastg
>NODE_1_length_147_cov_1.0000_ID_1:NODE_3038909_length_132_cov_1.0000_ID_6077817';
AGCCAGAGAGGACAATCATCGACCAGGTTGAAGTCAAGTACCATACCAATGACATACTTCATGGCCTCCCTTGCTTTGGTTGATGGAAGACATGACGCTGTAGGCGCAGACATGATGTCAGTTACCCGTAATCATCAAGGAGGCTTC
>NODE_1_length_147_cov_1.0000_ID_1':NODE_713450_length_144_cov_1.0000_ID_1426899';
GAAGCCTCCTTGATGATTACGGGTAACTGACATCATGTCTGCGCCTACAGCGTCATGTCTTCCATCAACCAAAGCAAGGGAGGCCATGAAGTATGTCATTGGTATGGTACTTGACTTCAACCTGGTCGATGATTGTCCTCTCTGGCT
>NODE_2_length_143_cov_1.0000_ID_3:NODE_1649577_length_402_cov_1.0000_ID_3299153;
TCTGTGTTTAATCGCATCGGCATGACCGACGTTGGATGCATTGCAACAAAGCGACGGCGATGACATCCATAGAGATGGCTTTTAGTCTAGATGACTATTTTTCCTTTTGGTCGGCATTCAGATAGCATGATTTGCCACTATTA
>NODE_2_length_143_cov_1.0000_ID_3':NODE_741621_length_160_cov_1.0000_ID_1483241;
TAATAGTGGCAAATCATGCTATCTGAATGCCGACCAAAAGGAAAAATAGTCATCTAGACTAAAAGCCATCTCTATGGATGTCATCGCCGTCGCTTTGTTGCAATGCATCCAACGTCGGTCATGCCGATGCGATTAAACACAGA
>NODE_3_length_159_cov_1.0000_ID_5:NODE_352489_length_177_cov_1.0000_ID_704977';
AAGATGGTGAAACAAACTTGGCGGATCTATTGACAAAGGTGGTTACGGGTCAGAAGAGATGGGATTTTTGCTATTGTTTATTTTGTTGAGTTGGTCTAACCCATGCCAGTCGAAAGAGATCGGAGGCTTTATAATATGGGTTGATGTATGGTAGAGTGT
```

**Comment by eitanyaffe** [comment]
OK, lets resolve this. Please generate an example that produces this error, so I can help you debug. 

Explanation of the error message: To convert the names I rely on a strict association between fasta and fastg, where contig2fastg converts every fasta entry to precisely two fastg entries (reverse and forward), keeping the same order. The error indicates the sequences do not match.

If the example files are too big you can share in some other media (email, dropbox, google drive). I tested the small examples you've generated (first 10 lines) and they fail only on a mapping issue (fastg entries not defined), which is expected since some target nodes (such as NODE_3038909) are only defined later on in the fastg file. When I temporarily edited the script to ignore mapping issues the script seemed to work fine.

**Comment by yuqing-feng** [comment]
The same problem to me. 

> OK, lets resolve this. Please generate an example that produces this error, so I can help you debug.
> 
> Explanation of the error message: To convert the names I rely on a strict association between fasta and fastg, where contig2fastg converts every fasta entry to precisely two fastg entries (reverse and forward), keeping the same order. The error indicates the sequences do not match.
> 
> If the example files are too big you can share in some other media (email, dropbox, google drive). I tested the small examples you've generated (first 10 lines) and they fail only on a mapping issue (fastg entries not defined), which is expected since some target nodes (such as NODE_3038909) are only defined later on in the fastg file. When I temporarily edited the script to ignore mapping issues the script seemed to work fine.

The same problme to me. I used megahit-core contig2fastg to convert the contig to fastg file. However, the rename_fastg.pl prompted "traversing fastg file to build map: k141.contigs.fa
sequence mismatch, make sure fasta and fastg are compatible".

fastg file:
https://drive.google.com/file/d/18RutjGDrGPLpQXC7qEjgJ1uU5REovOr9/view?usp=sharing
contig file:
https://drive.google.com/file/d/1ocwByCkDG36R2k4YN7B7AEcAz5L4NVL5/view?usp=sharing

**Comment by eitanyaffe** [comment]
This error does not come up on our side. I've downloaded the data and applied the script to it. It works fine on your data on both MacOS and Ubuntu.

**Comment by yuqing-feng** [comment]
> This error does not come up on our side. I've downloaded the data and applied the script to it. It works fine on your data on both MacOS and Ubuntu.

I found that the error due to the wrong order of the parameters. SAD

**Comment by eitanyaffe** [comment]
That's ok :)
